version: '3'
services:
  web:
    build: './shiny'
    ports:
      - "8787:8787"
      - "3838:3838"
      #- "0.0.0.0:8001:8001" #Makes webpage accessible from anywhere
    volumes:
      - ./shiny/shiny-files:/srv/shiny-server
    networks:
        my_app_network:
            ipv4_address: 172.28.1.2
  neo4j:
    image: "neo4j:latest"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_heap_max__size=4G
    container_name: neo4j_foodsDB
    networks:
        my_app_network:
            ipv4_address: 172.28.1.3
networks:
    my_app_network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
